export const COUNTRY_OPTIONS: { code: string; label: string }[] = [
  { code: "EG", label: "مصر" },
  { code: "SA", label: "السعودية" },
  { code: "AE", label: "الإمارات" },
  { code: "KW", label: "الكويت" },
  { code: "QA", label: "قطر" },
  { code: "BH", label: "البحرين" },
  { code: "OM", label: "عُمان" },
  { code: "JO", label: "الأردن" },
  { code: "LB", label: "لبنان" },
  { code: "SY", label: "سوريا" },
  { code: "IQ", label: "العراق" },
  { code: "YE", label: "اليمن" },
  { code: "PS", label: "فلسطين" },
  { code: "MA", label: "المغرب" },
  { code: "DZ", label: "الجزائر" },
  { code: "TN", label: "تونس" },
  { code: "TR", label: "تركيا" },
  { code: "US", label: "الولايات المتحدة" },
  { code: "CA", label: "كندا" },
  { code: "OTHER", label: "دولة أخرى" },
]
